import { dbQuery, dbConfigured } from "@/lib/db";
import type { SpxAdminIssue } from "@/lib/admin-spx-issues";

export type AdminIncidentStatus = "open" | "acked" | "resolved";

export type AdminIncidentRow = {
  id: string;
  fingerprint: string;
  severity: string;
  category: string;
  title: string;
  detail: string;
  status: AdminIncidentStatus;
  opened_at: string;
  acked_at: string | null;
  resolved_at: string | null;
  acked_by: string | null;
  mtta_ms: number | null;
};

let schemaReady: Promise<void> | null = null;

async function ensureIncidentSchema(): Promise<void> {
  if (!dbConfigured()) return;
  if (!schemaReady) {
    schemaReady = dbQuery(`
      CREATE TABLE IF NOT EXISTS admin_incidents (
        id TEXT PRIMARY KEY,
        fingerprint TEXT NOT NULL UNIQUE,
        severity TEXT NOT NULL,
        category TEXT NOT NULL,
        title TEXT NOT NULL,
        detail TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'open',
        opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        acked_at TIMESTAMPTZ,
        resolved_at TIMESTAMPTZ,
        acked_by TEXT,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
      CREATE INDEX IF NOT EXISTS idx_admin_incidents_status ON admin_incidents(status);
      CREATE INDEX IF NOT EXISTS idx_admin_incidents_opened ON admin_incidents(opened_at DESC);
    `).then(() => undefined);
  }
  await schemaReady;
}

function fingerprintFor(issue: SpxAdminIssue): string {
  return `${issue.category}:${issue.title}`;
}

/** Pure: which currently open/acked fingerprints should be auto-resolved, given
 *  the active issue set and (optional) namespace-ownership scope. Split out from
 *  syncAdminIncidents so the filtering logic — the part most likely to grow an
 *  off-by-one or scope bug — is unit-testable without a live Postgres connection. */
export function computeIncidentsToResolve(
  openRows: Array<{ fingerprint: string; category: string }>,
  activeFingerprints: Set<string>,
  resolveScope?: (category: string) => boolean
): string[] {
  return openRows
    .filter((row) => (!resolveScope || resolveScope(row.category)) && !activeFingerprints.has(row.fingerprint))
    .map((row) => row.fingerprint);
}

/**
 * Reconcile open incidents against the current active issue set.
 *
 * `options.resolveScope` makes the AUTO-RESOLVE step namespace-aware so two
 * independent reconcilers can share this table without clobbering each other:
 * each caller only resolves incidents in the categories it owns. The SPX
 * Operations dashboard owns everything EXCEPT `data-integrity*`; the
 * data-integrity cron owns only `data-integrity*`. When omitted, the legacy
 * behavior (resolve every open incident not in the active set) is preserved.
 */
export async function syncAdminIncidents(
  issues: SpxAdminIssue[],
  options?: { resolveScope?: (category: string) => boolean }
): Promise<void> {
  if (!dbConfigured()) return;
  await ensureIncidentSchema();

  const active = issues.filter((i) => i.severity === "critical" || i.severity === "warning");
  const activeFp = new Set(active.map(fingerprintFor));

  // Batched multi-row upsert via unnest() — this used to be N sequential dbQuery()
  // round trips (one INSERT per active issue). Called on every /api/admin/spx/dashboard
  // request, polled every 5s from the admin terminal tab (the default section) plus
  // two crons, the per-row loop held the small per-replica connection pool (max: 5,
  // see db.ts) open long enough under concurrent admin/audit load to starve unrelated
  // reads into the generic 35s query_timeout ("Query read timeout" — traced via Railway
  // runtime logs to a burst of ~111 of these across admin routes in one storm). One
  // round trip regardless of issue count fixes the contention without touching the
  // timeout/retry classification.
  if (active.length > 0) {
    // EDGE-12 fix: the incident `id` is generated by PostgreSQL via gen_random_uuid()
    // instead of being supplied by the application. This eliminates the
    // parallel-request PRIMARY KEY collision that arose when two concurrent writers
    // could derive the same application-side sequential ID. ON CONFLICT (fingerprint)
    // means only the first insert per unique fingerprint wins; subsequent upserts
    // update metadata without touching id.
    await dbQuery(
      `INSERT INTO admin_incidents (id, fingerprint, severity, category, title, detail, status, opened_at, updated_at)
       SELECT gen_random_uuid()::text, fp, sev, cat, ttl, det, 'open', NOW(), NOW()
       FROM unnest($1::text[], $2::text[], $3::text[], $4::text[], $5::text[]) AS t(fp, sev, cat, ttl, det)
       ON CONFLICT (fingerprint) DO UPDATE SET
         severity = EXCLUDED.severity,
         detail = EXCLUDED.detail,
         updated_at = NOW(),
         status = CASE WHEN admin_incidents.status = 'resolved' THEN 'open' ELSE admin_incidents.status END,
         resolved_at = CASE WHEN admin_incidents.status = 'resolved' THEN NULL ELSE admin_incidents.resolved_at END`,
      [
        active.map(fingerprintFor),
        active.map((i) => i.severity),
        active.map((i) => i.category),
        active.map((i) => i.title),
        active.map((i) => i.detail),
      ]
    );
  }

  const openRows = await dbQuery<{ fingerprint: string; category: string }>(
    `SELECT fingerprint, category FROM admin_incidents WHERE status IN ('open', 'acked')`
  );
  // Namespace ownership stays a JS predicate (unchanged semantics — skip incidents
  // this caller doesn't own so a scoped reconciler never resolves another
  // reconciler's incidents); only the resolve WRITE is batched into one UPDATE.
  const toResolve = computeIncidentsToResolve(openRows.rows, activeFp, options?.resolveScope);

  if (toResolve.length > 0) {
    await dbQuery(
      `UPDATE admin_incidents SET status = 'resolved', resolved_at = NOW(), updated_at = NOW()
       WHERE fingerprint = ANY($1::text[]) AND status IN ('open', 'acked')`,
      [toResolve]
    );
  }
}

export async function listOpenAdminIncidents(limit = 20): Promise<AdminIncidentRow[]> {
  if (!dbConfigured()) return [];
  await ensureIncidentSchema();
  const res = await dbQuery<{
    id: string;
    fingerprint: string;
    severity: string;
    category: string;
    title: string;
    detail: string;
    status: AdminIncidentStatus;
    opened_at: Date;
    acked_at: Date | null;
    resolved_at: Date | null;
    acked_by: string | null;
  }>(
    `SELECT id, fingerprint, severity, category, title, detail, status, opened_at, acked_at, resolved_at, acked_by
     FROM admin_incidents
     WHERE status IN ('open', 'acked')
     ORDER BY opened_at DESC
     LIMIT $1`,
    [limit]
  );

  const now = Date.now();
  return res.rows.map((row) => {
    const openedMs = new Date(row.opened_at).getTime();
    const ackedMs = row.acked_at ? new Date(row.acked_at).getTime() : null;
    return {
      id: row.id,
      fingerprint: row.fingerprint,
      severity: row.severity,
      category: row.category,
      title: row.title,
      detail: row.detail,
      status: row.status,
      opened_at: row.opened_at.toISOString(),
      acked_at: row.acked_at?.toISOString() ?? null,
      resolved_at: row.resolved_at?.toISOString() ?? null,
      acked_by: row.acked_by,
      mtta_ms: ackedMs != null ? ackedMs - openedMs : row.status === "open" ? now - openedMs : null,
    };
  });
}

export async function ackAdminIncident(id: string, actorEmail: string | null): Promise<boolean> {
  if (!dbConfigured()) return false;
  await ensureIncidentSchema();
  const res = await dbQuery(
    `UPDATE admin_incidents SET status = 'acked', acked_at = NOW(), acked_by = $2, updated_at = NOW()
     WHERE id = $1 AND status = 'open'`,
    [id, actorEmail]
  );
  return (res.rowCount ?? 0) > 0;
}

export async function resolveAdminIncident(id: string): Promise<boolean> {
  if (!dbConfigured()) return false;
  await ensureIncidentSchema();
  const res = await dbQuery(
    `UPDATE admin_incidents SET status = 'resolved', resolved_at = NOW(), updated_at = NOW()
     WHERE id = $1 AND status IN ('open', 'acked')`,
    [id]
  );
  return (res.rowCount ?? 0) > 0;
}
