/** Human-readable descriptions for internal API routes (cursor-api-analysis doc). */

export const INTERNAL_ROUTE_DESCRIPTIONS: Record<string, string> = {
  "/api/admin/analytics/spx": "Admin SPX analytics from Postgres (outcomes, signals)",
  "/api/admin/apis/dashboard": "Provider telemetry grid + live probes",
  "/api/admin/me": "Clerk user admin flag check",
  "/api/admin/spx/dashboard": "Admin SPX engine/desk/outcomes dashboard",
  "/api/cron/flow-ingest": "Cron: UW flow alerts → Postgres + SSE broadcast (CRON_SECRET)",
  "/api/cron/largo-cleanup": "Cron: purge stale Largo chat sessions",
  "/api/cron/nighthawk-edition": "Cron: build Night Hawk evening edition",
  "/api/cron/spx-evaluate": "Cron: evaluate SPX play + lotto during market hours",
  "/api/engine/[...path]": "Catch-all proxy to Blackout Engine (NEXT_PUBLIC_API_BASE)",
  "/api/engine/health": "Engine liveness probe",
  "/api/market/flows": "Flow tape — Postgres cache first, UW fallback",
  "/api/market/flows/stream": "SSE live flow stream to clients",
  "/api/market/health": "Polygon / UW / Postgres configured flags",
  "/api/market/heatmap": "Sector ETF performance + market movers",
  "/api/market/indices": "Fast SPX/VIX index quotes (Polygon)",
  "/api/market/largo/query": "Largo AI — Anthropic tool loop + provider orchestration",
  "/api/market/largo/session": "Load persisted Largo conversation from Postgres",
  "/api/market/lotto/today": "Pre-market lotto track state",
  "/api/market/news": "Benzinga headlines via Polygon",
  "/api/market/nighthawk/edition": "Night Hawk edition (Postgres + engine fallback)",
  "/api/market/nighthawk/hunt": "Agent hunt request (premium)",
  "/api/market/nighthawk/play-explain": "Claude briefing for a playbook play",
  "/api/market/platform/snapshot": "Cross-service snapshot (SPX, flows, Night Hawk)",
  "/api/market/spx/commentary": "Claude desk commentary (auth required)",
  "/api/market/spx/desk": "Full SPX Sniper desk (Polygon + UW)",
  "/api/market/spx/flow": "Flow lane — GEX, tape, dark pool, NOPE",
  "/api/market/spx/merged": "Merged pulse + flow + desk",
  "/api/market/spx/outcomes": "Play outcome stats + adaptive gates",
  "/api/market/spx/play": "SPX play engine (BUY/HOLD/TRIM/SELL)",
  "/api/market/spx/pulse": "Fast pulse lane — price, session, internals",
  "/api/market/spx/signals": "Recent SPX signal log",
  "/api/membership/sync": "Sync Clerk tier from Whop membership",
  "/api/webhook/whop": "Whop membership webhook handler",
};

export const ROUTE_PROVIDER_CHAIN: Record<string, string> = {
  "/api/market/spx/pulse": "Polygon indices, stock snapshots, EMA/SMA, VWAP, market status",
  "/api/market/spx/flow": "UW GEX, max pain, NOPE, flow, dark pool, IV · Polygon GEX fallback",
  "/api/market/spx/desk": "buildSpxDesk → Polygon + UW + Finnhub macro",
  "/api/market/spx/play": "Polygon options chain + Claude + Postgres outcomes",
  "/api/market/spx/commentary": "Desk snapshot → Anthropic Claude",
  "/api/market/flows": "Postgres flow cache · UW /api/option-trades/flow-alerts",
  "/api/market/news": "Polygon /benzinga/v2/news",
  "/api/market/largo/query": "Anthropic tool loop → Polygon/UW/Finnhub/web-search/Postgres",
  "/api/market/nighthawk/edition": "Edition builder → Polygon + UW + Benzinga + Claude + Postgres",
  "/api/market/nighthawk/play-explain": "Anthropic Claude + dossier context",
  "/api/market/heatmap": "Polygon movers + sector ETF snapshots",
  "/api/market/indices": "Polygon /v3/snapshot/indices",
};

export const LARGO_TOOL_PROVIDERS: Record<string, string> = {
  get_quote: "Polygon",
  get_technicals: "Polygon",
  get_peer_rs: "Polygon",
  get_seasonality: "Polygon + UW",
  get_qqq_relative_strength: "Polygon",
  get_oi_per_strike: "Polygon → UW fallback",
  get_oi_per_expiry: "Polygon → UW fallback",
  get_max_pain: "Polygon → UW fallback",
  get_greeks: "Polygon → UW fallback",
  get_atm_chains: "Polygon → UW fallback",
  get_options_chain: "Polygon → UW fallback",
  get_options_volume: "UW",
  get_options_flow: "UW (+ SPX desk cache)",
  get_net_prem_ticks: "UW",
  get_nope: "UW",
  get_flow_per_strike: "UW",
  get_flow_expiry_breakdown: "UW",
  get_dark_pool: "UW",
  get_lit_flow: "UW",
  get_unusual_trades: "UW",
  get_market_oi_change: "UW",
  get_top_net_impact: "UW",
  get_iv_stats: "Polygon → UW fallback",
  get_iv_term_structure: "Polygon → UW",
  get_volatility_regime: "UW",
  get_realized_vol: "UW",
  get_risk_reversal_skew: "UW",
  get_vol_anomaly: "UW",
  get_market_context: "Polygon + UW",
  get_market_breadth: "Polygon",
  get_sector_flow: "UW sector tide",
  get_market_movers: "Polygon + UW",
  get_economic_calendar: "Finnhub + static macro",
  get_etf_flow: "UW ETF tide/in-outflow",
  get_company_profile: "Finnhub + UW + Polygon",
  get_financials: "UW + Finnhub",
  get_earnings: "UW + Finnhub",
  get_analyst_ratings: "Finnhub",
  get_news: "Benzinga → Polygon → Finnhub → UW",
  get_web_search: "Tavily / Serper / Brave",
  get_short_interest: "Polygon → UW",
  get_short_data: "Polygon + UW",
  get_insider_flow: "UW + Finnhub",
  get_congress_trades: "UW",
  get_screener: "UW",
  get_spx_structure: "Platform SPX service",
  get_spx_play: "Platform SPX service",
  get_open_plays: "Postgres",
  get_trade_history: "Postgres",
  get_setup_stats: "Postgres",
  get_postgres_flows: "Postgres",
  get_signal_log: "Postgres",
  get_lotto_state: "SPX lotto engine",
  get_nighthawk_edition: "Platform Night Hawk service",
  get_flow_tape: "Platform flow service",
  get_platform_snapshot: "Platform cross-access",
  get_gex: "Polygon → UW",
  get_greek_flow: "UW",
  get_option_contract: "UW",
  get_stock_state: "UW",
  get_ownership: "UW",
  get_institutional: "UW",
  get_etf_detail: "UW ETFs",
  get_market_stats: "UW market endpoints",
  get_nbbo: "Polygon",
  get_uw_bars: "UW OHLC",
  get_uw_technicals: "UW technical-indicator",
  get_earnings_market: "UW earnings pre/post",
  get_congress_unusual: "UW",
  get_vix_term: "Polygon indices → UW VIX term",
  get_dividends: "UW companies",
  get_global_flow: "UW flow-alerts",
  get_fda_calendar: "UW",
  get_ipo_calendar: "Finnhub",
  get_earnings_history: "UW",
};
