import type { RestEndpoint, RestEndpointSection } from "@/lib/polygon-docs-rest-types";

export type { RestEndpoint, RestEndpointSection };

export const STOCKS_REST_SECTIONS: RestEndpointSection[] = [
  {
    id: "tickers",
    title: "Tickers",
    endpoints: [
      {
        name: "All Tickers",
        method: "GET",
        path: "/v3/reference/tickers",
        description:
          "Comprehensive list of ticker symbols across asset classes. Each entry includes symbol, name, market, currency, and active status.",
        useCases: "Asset discovery, data integration, filtering, application development.",
        docPath: "/rest/stocks/tickers/all-tickers",
      },
      {
        name: "Ticker Overview",
        method: "GET",
        path: "/v3/reference/tickers/{ticker}",
        description:
          "Deep company fundamentals for a single active ticker: exchange, CIK, FIGI, market cap, industry, key dates, branding assets. Use All Tickers with active=false for delisted.",
        useCases: "Company research, data integration, app enhancement, due diligence.",
        docPath: "/rest/stocks/tickers/ticker-overview",
      },
      {
        name: "Ticker Types",
        method: "GET",
        path: "/v3/reference/tickers/types",
        description: "All ticker types supported by Massive — classifications across asset classes, markets, and instruments.",
        useCases: "Data classification, filtering, educational reference, system integration.",
        docPath: "/rest/stocks/tickers/ticker-types",
      },
      {
        name: "Related Tickers",
        method: "GET",
        path: "/v1/related-companies/{ticker}",
        description:
          "Peers and thematically similar tickers from news coverage and returns analysis.",
        useCases: "Peer identification, comparative analysis, portfolio diversification, market research.",
        docPath: "/rest/stocks/tickers/related-tickers",
      },
    ],
  },
  {
    id: "aggregates",
    title: "Aggregate Bars (OHLC)",
    endpoints: [
      {
        name: "Custom Bars",
        method: "GET",
        path: "/v2/aggs/ticker/{stocksTicker}/range/{multiplier}/{timespan}/{from}/{to}",
        description:
          "Historical OHLC + volume over a custom date range and interval (ET). Pre-market, regular, and after-hours. Empty intervals = no qualifying trades.",
        useCases: "Charting, technical analysis, backtesting, market research.",
        docPath: "/rest/stocks/aggregates/custom-bars",
      },
      {
        name: "Daily Market Summary",
        method: "GET",
        path: "/v2/aggs/grouped/locale/us/market/stocks/{date}",
        description: "Daily OHLC, volume, and VWAP for all U.S. stocks on a given trading date.",
        useCases: "Market overview, bulk processing, historical research, portfolio comparison.",
        docPath: "/rest/stocks/aggregates/daily-market-summary",
      },
      {
        name: "Daily Ticker Summary",
        method: "GET",
        path: "/v1/open-close/{stocksTicker}/{date}",
        description: "Open/close for a ticker on a date, plus pre-market and after-hours prices.",
        useCases: "Daily performance, historical collection, after-hours insights, portfolio tracking.",
        docPath: "/rest/stocks/aggregates/daily-ticker-summary",
      },
      {
        name: "Previous Day Bar",
        method: "GET",
        path: "/v2/aggs/ticker/{stocksTicker}/prev",
        description: "Previous session OHLC + volume for baseline comparison.",
        useCases: "Baseline comparison, technical analysis, market research, daily reporting.",
        docPath: "/rest/stocks/aggregates/previous-day-bar",
      },
    ],
  },
  {
    id: "snapshots",
    title: "Snapshots",
    endpoints: [
      {
        name: "Single Ticker Snapshot",
        method: "GET",
        path: "/v2/snapshot/locale/us/markets/stocks/tickers/{stocksTicker}",
        description:
          "Latest trade, quote, and aggs (minute, day, prev day) for one ticker. Cleared 3:30 AM EST; repopulates from ~4:00 AM EST.",
        useCases: "Focused monitoring, real-time analysis, price alerts, investor relations.",
        docPath: "/rest/stocks/snapshots/single-ticker-snapshot",
      },
      {
        name: "Full Market Snapshot",
        method: "GET",
        path: "/v2/snapshot/locale/us/markets/stocks/tickers",
        description: "10,000+ active tickers in one response — pricing, volume, trade activity.",
        useCases: "Market overview, bulk analysis, heatmaps/dashboards, automated monitoring.",
        docPath: "/rest/stocks/snapshots/full-market-snapshot",
      },
      {
        name: "Unified Snapshot",
        method: "GET",
        path: "/v3/snapshot",
        description: "Multi-asset snapshots (stocks, options, forex, crypto) in one request.",
        useCases: "Cross-market analysis, diversified monitoring, global insights, multi-asset strategies.",
        docPath: "/rest/stocks/snapshots/unified-snapshot",
      },
      {
        name: "Top Market Movers",
        method: "GET",
        path: "/v2/snapshot/locale/us/markets/stocks/{direction}",
        description: "Top 20 gainers or losers by % change since prior close. Min volume 10,000.",
        useCases: "Movers identification, trading strategies, sentiment, portfolio adjustments.",
        docPath: "/rest/stocks/snapshots/top-market-movers",
      },
    ],
  },
  {
    id: "trades-quotes",
    title: "Trades & Quotes",
    endpoints: [
      {
        name: "Trades",
        method: "GET",
        path: "/v3/trades/{stockTicker}",
        description: "Tick-level trade history: price, size, exchange, conditions, timestamps.",
        useCases: "Intraday analysis, algo trading, microstructure research, compliance.",
        docPath: "/rest/stocks/trades-quotes/trades",
      },
      {
        name: "Last Trade",
        method: "GET",
        path: "/v2/last/trade/{stocksTicker}",
        description: "Most recent trade for a ticker.",
        useCases: "Trade monitoring, price updates, market snapshot.",
        docPath: "/rest/stocks/trades-quotes/last-trade",
      },
      {
        name: "Quotes",
        method: "GET",
        path: "/v3/quotes/{stockTicker}",
        description: "Historical NBBO quotes over a time range — bid/ask, sizes, exchanges, timestamps.",
        useCases: "Quote analysis, liquidity evaluation, algo backtesting, strategy refinement.",
        docPath: "/rest/stocks/trades-quotes/quotes",
      },
      {
        name: "Last Quote",
        method: "GET",
        path: "/v2/last/nbbo/{stocksTicker}",
        description: "Latest NBBO quote — bid/ask, sizes, exchange, timestamp.",
        useCases: "Price display, spread analysis, market monitoring.",
        docPath: "/rest/stocks/trades-quotes/last-quote",
      },
    ],
  },
  {
    id: "indicators",
    title: "Technical Indicators",
    endpoints: [
      {
        name: "SMA",
        method: "GET",
        path: "/v1/indicators/sma/{stockTicker}",
        description: "Simple Moving Average over a defined range.",
        useCases: "Trend analysis, crossover signals, support/resistance, entry/exit timing.",
        docPath: "/rest/stocks/technical-indicators/simple-moving-average",
      },
      {
        name: "EMA",
        method: "GET",
        path: "/v1/indicators/ema/{stockTicker}",
        description: "Exponential Moving Average — heavier weight on recent prices.",
        useCases: "Trend identification, EMA crossovers, dynamic support/resistance.",
        docPath: "/rest/stocks/technical-indicators/exponential-moving-average",
      },
      {
        name: "MACD",
        method: "GET",
        path: "/v1/indicators/macd/{stockTicker}",
        description: "Moving Average Convergence/Divergence momentum indicator.",
        useCases: "Momentum analysis, crossover signals, overbought/oversold, trend confirmation.",
        docPath: "/rest/stocks/technical-indicators/moving-average-convergence-divergence",
      },
      {
        name: "RSI",
        method: "GET",
        path: "/v1/indicators/rsi/{stockTicker}",
        description: "Relative Strength Index (0–100) — speed and magnitude of price changes.",
        useCases: "Overbought/oversold detection, divergence, trend confirmation.",
        docPath: "/rest/stocks/technical-indicators/relative-strength-index",
      },
    ],
  },
  {
    id: "market-ops",
    title: "Market Operations",
    endpoints: [
      {
        name: "Exchanges",
        method: "GET",
        path: "/v3/reference/exchanges",
        description: "Known exchanges with identifiers, names, market types, and attributes.",
        useCases: "Data mapping, market coverage, app development, regulatory compliance.",
        docPath: "/rest/stocks/market-operations/exchanges",
      },
      {
        name: "Market Holidays",
        method: "GET",
        path: "/v1/marketstatus/upcoming",
        description: "Forward-looking market holidays and open/close times.",
        useCases: "Schedule adjustments, holiday calendars, maintenance planning, user notifications.",
        docPath: "/rest/stocks/market-operations/market-holidays",
      },
      {
        name: "Market Status",
        method: "GET",
        path: "/v1/marketstatus/now",
        description: "Real-time open/closed/pre-market/after-hours status for exchanges and markets.",
        useCases: "Real-time monitoring, algo scheduling, UI updates, operational planning.",
        docPath: "/rest/stocks/market-operations/market-status",
      },
      {
        name: "Condition Codes",
        method: "GET",
        path: "/v3/reference/conditions",
        description: "Unified trade and quote conditions from CTA, UTP, OPRA, FINRA — how they affect OHLC/volume.",
        useCases: "Data interpretation, filtering, algo adjustments, compliance.",
        docPath: "/rest/stocks/market-operations/condition-codes",
      },
    ],
  },
  {
    id: "corporate-actions",
    title: "Corporate Actions",
    endpoints: [
      {
        name: "IPOs",
        method: "GET",
        path: "/vX/reference/ipos",
        description: "IPO events from 2008 — upcoming and historical, status filters (pending, new, rumors, historical).",
        useCases: "IPO research, market trends, investment screening, historical comparison.",
        docPath: "/rest/stocks/corporate-actions/ipos",
      },
      {
        name: "Splits (Deprecated)",
        method: "GET",
        path: "/v3/reference/splits",
        description: "Historical split events — used internally for price adjustments in Aggregates API.",
        useCases: "Historical analysis, price adjustments, data consistency, modeling.",
        docPath: "/rest/stocks/corporate-actions/splits-deprecated",
        deprecated: true,
      },
      {
        name: "Splits",
        method: "GET",
        path: "/stocks/v1/splits",
        description: "Historical splits with adjustment factors for normalizing prices to today's share basis.",
        useCases: "Historical analysis, price adjustments, data consistency, modeling.",
        docPath: "/rest/stocks/corporate-actions/splits",
      },
      {
        name: "Dividends (Deprecated)",
        method: "GET",
        path: "/v3/reference/dividends",
        description: "Historical cash dividends — declaration, ex-date, record, pay dates, payout amounts.",
        useCases: "Income analysis, total return, dividend strategies, tax planning.",
        docPath: "/rest/stocks/corporate-actions/dividends-deprecated",
        deprecated: true,
      },
      {
        name: "Dividends",
        method: "GET",
        path: "/stocks/v1/dividends",
        description: "Historical dividends with adjustment factors for normalizing historical prices.",
        useCases: "Income analysis, total return, dividend strategies, tax planning.",
        docPath: "/rest/stocks/corporate-actions/dividends",
      },
      {
        name: "Ticker Events",
        method: "GET",
        path: "/vX/reference/tickers/{id}/events",
        description: "Experimental timeline of ticker changes (renames, rebranding) by ticker, CUSIP, or FIGI.",
        useCases: "Symbol change history, data continuity, record-keeping.",
        docPath: "/rest/stocks/corporate-actions/ticker-events",
      },
    ],
  },
  {
    id: "fundamentals",
    title: "Fundamentals",
    endpoints: [
      {
        name: "Balance Sheets",
        method: "GET",
        path: "/stocks/financials/v1/balance-sheets",
        description: "Quarterly and annual balance sheets — assets, liabilities, equity point-in-time snapshots.",
        useCases: "Financial analysis, valuation, asset/debt assessment, equity research.",
        docPath: "/rest/stocks/fundamentals/balance-sheets",
      },
      {
        name: "Cash Flow Statements",
        method: "GET",
        path: "/stocks/financials/v1/cash-flow-statements",
        description: "Operating, investing, financing cash flows with TTM calculations.",
        useCases: "Cash flow analysis, liquidity, operational efficiency, investment tracking.",
        docPath: "/rest/stocks/fundamentals/cash-flow-statements",
      },
      {
        name: "Income Statements",
        method: "GET",
        path: "/stocks/financials/v1/income-statements",
        description: "Revenue, expenses, net income across quarterly, annual, and TTM periods.",
        useCases: "Profitability analysis, revenue trends, expense evaluation, earnings assessment.",
        docPath: "/rest/stocks/fundamentals/income-statements",
      },
      {
        name: "Ratios",
        method: "GET",
        path: "/stocks/financials/v1/ratios",
        description: "Valuation, profitability, liquidity, leverage ratios using TTM financials + daily prices.",
        useCases: "Valuation, comparative analysis, financial health, investment screening.",
        docPath: "/rest/stocks/fundamentals/ratios",
      },
      {
        name: "Short Interest",
        method: "GET",
        path: "/stocks/v1/short-interest",
        description: "FINRA short interest on two-week cadence — shares sold short not yet covered.",
        useCases: "Sentiment analysis, squeeze prediction, risk management, strategy refinement.",
        docPath: "/rest/stocks/fundamentals/short-interest",
      },
      {
        name: "Short Volume",
        method: "GET",
        path: "/stocks/v1/short-volume",
        description: "Daily aggregated short sale volume from off-exchange venues and ATS.",
        useCases: "Intraday sentiment, short-sale trends, liquidity analysis.",
        docPath: "/rest/stocks/fundamentals/short-volume",
      },
      {
        name: "Float",
        method: "GET",
        path: "/stocks/vX/float",
        description: "Latest free float — shares available for public trading after excluding strategic holders.",
        useCases: "Liquidity analysis, volatility modeling, position sizing, market impact.",
        docPath: "/rest/stocks/fundamentals/float",
      },
    ],
  },
  {
    id: "filings",
    title: "Filings & Disclosures",
    endpoints: [
      {
        name: "EDGAR Index",
        method: "GET",
        path: "/stocks/filings/vX/index",
        description: "Master SEC EDGAR index — form types, dates, CIKs, tickers, accession numbers, SEC.gov links.",
        useCases: "Filing discovery, compliance alerts, due diligence, competitive intelligence.",
        docPath: "/rest/stocks/filings-and-disclosures/edgar-index",
      },
      {
        name: "10-K Sections",
        method: "GET",
        path: "/stocks/filings/10-K/vX/sections",
        description: "Plain-text extracts from 10-K — Business, Risk Factors, and other narrative sections.",
        useCases: "NLP, risk profiling, competitive benchmarking, LLM knowledge bases.",
        docPath: "/rest/stocks/filings-and-disclosures/10-k-sections",
      },
      {
        name: "8-K Text",
        method: "GET",
        path: "/stocks/filings/8-K/vX/text",
        description: "Parsed plain-text from 8-K material event items — acquisitions, leadership, contracts.",
        useCases: "Event detection, event-driven trading, M&A tracking, corporate action timelines.",
        docPath: "/rest/stocks/filings-and-disclosures/8-k-text",
      },
      {
        name: "13-F Filings",
        method: "GET",
        path: "/stocks/filings/vX/13-F",
        description: "Institutional holdings from Form 13-F ($100M+ managers) — positions, values, discretion.",
        useCases: "Institutional ownership trends, hedge fund replication, overlap analysis, smart-money flows.",
        docPath: "/rest/stocks/filings-and-disclosures/13-f-filings",
      },
      {
        name: "Risk Factors",
        method: "GET",
        path: "/stocks/filings/vX/risk-factors",
        description: "Standardized, machine-readable risk factor disclosures with consistent taxonomy.",
        useCases: "Risk trend analysis, cross-company comparison, classification models, investment research.",
        docPath: "/rest/stocks/filings-and-disclosures/risk-factors",
      },
      {
        name: "Risk Categories",
        method: "GET",
        path: "/stocks/taxonomies/vX/risk-factors",
        description: "Full hierarchical taxonomy for classifying SEC filing risk factors.",
        useCases: "Classification models, category analytics, cross-company comparison, thematic monitoring.",
        docPath: "/rest/stocks/filings-and-disclosures/risk-categories",
      },
      {
        name: "Form 3",
        method: "GET",
        path: "/stocks/filings/vX/form-3",
        description: "Initial insider beneficial ownership when subject to Section 16 reporting.",
        useCases: "New insider positions, executive ownership, due diligence, compliance.",
        docPath: "/rest/stocks/filings-and-disclosures/form-3",
      },
      {
        name: "Form 4",
        method: "GET",
        path: "/stocks/filings/vX/form-4",
        description: "Insider transaction changes within two business days — buys, sells, exercises, grants.",
        useCases: "Insider monitoring, management confidence, Section 16 compliance, behavior studies.",
        docPath: "/rest/stocks/filings-and-disclosures/form-4",
      },
    ],
  },
  {
    id: "news",
    title: "News",
    endpoints: [
      {
        name: "News",
        method: "GET",
        path: "/v2/reference/news",
        description:
          "Recent news for a ticker with summaries, sources, and sentiment. Polygon-native news (Benzinga is a separate subscription).",
        useCases: "Sentiment analysis, investment research, automated monitoring, portfolio strategy.",
        docPath: "/rest/stocks/news/news",
      },
    ],
  },
];

/** Quick-jump links for the page TOC */
export const STOCKS_REST_TOC = STOCKS_REST_SECTIONS.map((s) => ({
  id: s.id,
  title: s.title,
  count: s.endpoints.length,
}));