/**
 * Night Hawk data-source registry — tracks which API endpoints power the evening playbook.
 * Keep in sync with market-wide.ts + dossier.ts call sites.
 */
export const NIGHTHAWK_DATA_SOURCES = {
  market: {
    wired: [
      { provider: "uw", endpoint: "/api/market/market-tide", use: "Session call/put premium bias" },
      { provider: "uw", endpoint: "/api/option-trades/flow-alerts", use: "Stock flows + hot chains" },
      { provider: "uw", endpoint: "/api/stock/{t}/flow-alerts", use: "Index/ETF flow" },
      { provider: "uw", endpoint: "/api/market/{sector}/sector-tide", use: "Sector rotation" },
      { provider: "uw", endpoint: "/api/etf/{t}/tide", use: "SPY/QQQ ETF tide" },
      { provider: "polygon", endpoint: "Benzinga news (via polygon-largo)", use: "Market + ticker news" },
      { provider: "uw", endpoint: "/api/market/top-net-impact", use: "Names driving net premium" },
      { provider: "uw", endpoint: "/api/market/total-options-volume", use: "Total market options vol" },
      { provider: "uw", endpoint: "/api/market/oi-change", use: "Market-wide OI shifts" },
      { provider: "uw", endpoint: "/api/group-greek-flow/mag7", use: "Mag7 dealer greek flow" },
      { provider: "uw", endpoint: "/api/macro-indicators", use: "Macro indicator snapshot" },
      { provider: "polygon", endpoint: "/v3/snapshot/options/{underlying}", use: "GEX/max pain (primary)" },
      { provider: "polygon", endpoint: "VIX index snapshots", use: "VIX term structure (primary)" },
      { provider: "polygon", endpoint: "/v2/aggs/ticker/I:SPX|I:VIX/range/1/day", use: "SPX/VIX daily" },
      { provider: "polygon", endpoint: "/v1/market/sector-performance", use: "Sector strength/weakness" },
      { provider: "polygon", endpoint: "/v2/reference/news", use: "Market news fallback" },
      { provider: "static", endpoint: "macro-events.ts", use: "Tomorrow macro (curated schedule)" },
      { provider: "uw", endpoint: "/api/earnings/premarket|afterhours", use: "Tomorrow earnings" },
      { provider: "polygon", endpoint: "/v2/aggs/grouped/locale/us/market/stocks/{date}", use: "Full-market breadth" },
      { provider: "uw", endpoint: "/api/predictions/insiders", use: "Prediction consensus (market)" },
      { provider: "postgres", endpoint: "market_regime + flow_anomalies + platform_briefs", use: "Platform intel snapshot" },
      { provider: "platform", endpoint: "marketPlatform.spx + flows", use: "Live desk + HELIX tape in synthesis" },
    ],
    available: [
      { provider: "uw", endpoint: "/api/market/correlations", use: "Cross-asset correlations" },
      { provider: "uw", endpoint: "/api/market/vix-term-structure", use: "VIX term UW fallback (Polygon primary)" },
    ],
  },
  dossier: {
    wired: [
      { provider: "uw", endpoint: "/api/stock/{t}/flow-alerts", use: "Ticker flow + strike stacks" },
      { provider: "uw", endpoint: "/api/stock/{t}/darkpool", use: "Dark pool prints" },
      { provider: "uw", endpoint: "/api/stock/{t}/oi-change", use: "OI change by strike" },
      { provider: "gex-cache", endpoint: "getGexPositioning()", use: "GEX/max pain (shared with Heatmap/Largo)" },
      { provider: "uw", endpoint: "/api/stock/{t}/spot-exposures/strike", use: "GEX ladder (cold-cache fallback)" },
      { provider: "uw", endpoint: "/api/stock/{t}/max-pain", use: "Max pain (fallback)" },
      { provider: "polygon", endpoint: "VIX IV rank percentile", use: "IV rank (indices)" },
      { provider: "uw", endpoint: "/api/stock/{t}/volatility/stats", use: "IV rank (equities fallback)" },
      { provider: "uw", endpoint: "/api/stock/{t}/implied-volatility-term-structure", use: "IV term" },
      { provider: "uw", endpoint: "/api/stock/{t}/volatility/realized", use: "Realized vol" },
      { provider: "uw", endpoint: "/api/stock/{t}/historical-risk-reversal-skew", use: "Skew" },
      { provider: "uw", endpoint: "/api/stock/{t}/flow-per-expiry", use: "DTE flow distribution" },
      { provider: "uw", endpoint: "/api/congress/recent-trades", use: "Congressional flow" },
      { provider: "uw", endpoint: "/api/congress/unusual-trades", use: "Unusual congressional trades" },
      { provider: "uw", endpoint: "/api/institution/{t}/ownership", use: "Institutional holders" },
      { provider: "uw", endpoint: "/api/predictions/smart-money", use: "Smart-money prediction bias" },
      { provider: "uw", endpoint: "/api/predictions/whales", use: "Whale prediction bias" },
      { provider: "uw", endpoint: "/api/screener/stocks", use: "Screener confirmation" },
      { provider: "polygon", endpoint: "MTF aggs + indicators", use: "Technicals S/R gaps breakouts" },
      { provider: "uw", endpoint: "/api/insider/transactions", use: "Insider buy signal (+2 score)" },
      { provider: "polygon", endpoint: "/v3/reference/tickers/{t}", use: "Sector / industry" },
      { provider: "polygon", endpoint: "Benzinga financials + catalysts + PT", use: "Fundamentals + events" },
      { provider: "postgres", endpoint: "flow_alerts", use: "Multi-day flow streak" },
      { provider: "uw", endpoint: "/api/stock/{t}/fda-calendar", use: "FDA catalysts (conditional)" },
      { provider: "uw", endpoint: "/api/stock/{t}/greek-flow", use: "Per-ticker dealer greek flow (scoring + thesis)" },
    ],
    available: [
      { provider: "heatmap", endpoint: "flow-per-strike overlay", use: "Strike-level flow vs GEX" },
    ],
  },
} as const;
