/**
 * SPX Slayer — Playbook Registry, Phase 1 (SHADOW MODE ONLY).
 *
 * Static, typed catalog of the first 3 named playbooks out of the 12 described in
 * `docs/spx/SPX-Slayer-Playbook-Design-v1.docx` Section 6 ("The Twelve Playbooks (Full
 * Catalog)"). This is pure DATA — no evaluation/matching logic lives here (that's
 * `playbook-shadow-matcher.ts`, a sibling file in this directory).
 *
 * WHY 3, NOT 12: the design doc's own Section 12 ("Migration Roadmap (Shadow → Live)")
 * defines "Phase 1 — Shadow: Matcher runs alongside legacy engine; log would-be
 * playbook_id without changing BUY" as the first migration step, and Section 14
 * ("Validation Checklist for Other AIs") explicitly asks reviewers to weigh in on
 * "Are twelve playbooks too many for 0DTE SPX?" and "Suggested priority order for
 * Phase 1-3 implementation" before a full 12-playbook rollout. Starting this narrow
 * (the 3 highest-frequency, most code-computable setups: a reclaim, a reject, and an
 * opening-range breakout) is the proven-safe incremental pattern this codebase already
 * uses for every other SPX Slayer shadow addition — see
 * `spx-signals-shadow.ts` (flow_anomalies, the first shadow factor, landed alone before
 * 4 more followed one PR at a time) and `spx-signals-shadow-skew.ts`'s own module doc,
 * which cites the same "prove it in isolation first" rationale. Playbooks PB-04 through
 * PB-12 are catalogued in the design doc but deliberately NOT added here — a future,
 * separately-reviewed PR extends this array once PB-01/02/03 have shadow evidence.
 *
 * SOURCE OF TRUTH: every `preconditions`/`trigger`/`invalidation`/`sessionWindow` string
 * below is copied VERBATIM from the design doc's Section 6 PB-01/PB-02/PB-03 entries
 * (generated by `scripts/generate-playbook-design-docx.py`, `add_playbooks()`) — not
 * paraphrased from any other source. If the design doc's wording for these 3 playbooks
 * ever changes, update this file to match, not the other way around.
 *
 * SHADOW-MODE / INERTNESS: this file (and its sibling `playbook-shadow-matcher.ts`) is
 * never imported by `spx-signals.ts`, `spx-play-gates.ts`, or `spx-play-engine.ts`'s live
 * scoring/gating logic — see `playbook-shadow-matcher.ts`'s own module doc for the full
 * inertness proof (the same `git grep`-verifiable guarantee `spx-signals-shadow.ts`
 * established for the original shadow-factor framework).
 */

/** Stable per-playbook identity, used as `factor_name`/`playbook_id` in telemetry. */
export type PlaybookId = "PB-01" | "PB-02" | "PB-03" | "PB-04" | "PB-08";

/**
 * The design doc's free-text "Direction:" field for PB-01/02/03 is deliberately richer
 * than a 3-way enum ("Long or Short", "Short (or long inverse)", "Break direction") — see
 * each entry's `preconditions`/`trigger`/`invalidation` text for the full nuance. This
 * enum is the code-computable simplification the matcher needs to pick a side:
 * "either" means the SAME named pattern can fire long or short depending on which way
 * price is moving relative to the playbook's anchor level (VWAP for PB-01, the opening
 * range for PB-03); "short" means PB-02's primary posture per the design doc (a long
 * inverse variant is described but not modeled in Phase 1's matcher).
 */
export type PlaybookDirection = "long" | "short" | "either";

/** Typical session window from the design doc, in ET hour/minute — half-open [start, end). */
export type PlaybookSessionWindow = {
  startEtHour: number;
  startEtMin: number;
  endEtHour: number;
  endEtMin: number;
};

export type PlaybookDefinition = {
  id: PlaybookId;
  name: string;
  direction: PlaybookDirection;
  /** Verbatim "Regime tags:" text from the design doc's Section 6 entry. */
  regimeTags: string;
  /** Verbatim "Preconditions:" text from the design doc's Section 6 entry. */
  preconditions: string;
  /** Verbatim "Trigger:" text from the design doc's Section 6 entry. */
  trigger: string;
  /** Verbatim "Invalidation:" text from the design doc's Section 6 entry. */
  invalidation: string;
  sessionWindow: PlaybookSessionWindow;
};

/**
 * Registry order is significant: `playbook-shadow-matcher.ts`'s `pickPrimaryPlaybook()`
 * deterministically picks the FIRST entry (in this array's order) whose trigger fired
 * when more than one playbook triggers on the same tick — see that function's doc for why
 * array order (not e.g. alphabetical id or a priority field) was chosen as the tie-break.
 */
export const PLAYBOOK_REGISTRY: readonly PlaybookDefinition[] = [
  {
    id: "PB-01",
    name: "VWAP Reclaim",
    direction: "either",
    regimeTags: "Trend / recovery after flush",
    preconditions:
      "Price below VWAP ≥15m, then reclaims with volume; EMA9 curling toward VWAP.",
    trigger: "Close above VWAP + hold 2 consecutive 3m bars; flow skew aligns.",
    invalidation: "Close back below VWAP on volume; regime flips to chop.",
    sessionWindow: { startEtHour: 9, startEtMin: 45, endEtHour: 14, endEtMin: 0 },
  },
  {
    id: "PB-02",
    name: "VWAP Reject",
    direction: "short",
    regimeTags: "Weak trend / distribution",
    preconditions: "Rally into VWAP from below; repeated rejections at VWAP band.",
    trigger: "3m close rejection wick + negative net flow spike.",
    invalidation: "Acceptance above VWAP (2 closes).",
    sessionWindow: { startEtHour: 10, startEtMin: 0, endEtHour: 15, endEtMin: 0 },
  },
  {
    id: "PB-03",
    name: "Opening Range Breakout",
    direction: "either",
    regimeTags: "Opening drive",
    preconditions: "First 15–30m range defined; GEX not pinning inside range.",
    trigger: "Break of OR high/low with flow confirmation; spot clears flip level.",
    invalidation: "Re-entry inside OR; halt feed degraded (optional strict mode).",
    sessionWindow: { startEtHour: 9, startEtMin: 35, endEtHour: 10, endEtMin: 30 },
  },
  // PB-04/PB-08 added on prod-outcome evidence (docs/spx/PLAYBOOK-EVIDENCE-BASE.md):
  // ~all logged entries happened in gamma mean_revert (pin) regime and lost fighting it,
  // and the 14:00+ ET afternoon was the only net-positive window in the track record.
  {
    id: "PB-04",
    name: "Gamma Pin Fade",
    direction: "either",
    regimeTags: "High pin / low vol midday",
    preconditions: "Spot between major walls; charm decay elevated; low ATR.",
    trigger: "Touch of wall + rejection; confluence on mean-reversion factors.",
    invalidation: "Sustained breakout through wall with flow.",
    sessionWindow: { startEtHour: 11, startEtMin: 30, endEtHour: 15, endEtMin: 0 },
  },
  {
    id: "PB-08",
    name: "Power Hour Momentum",
    direction: "either",
    regimeTags: "Power hour",
    preconditions: "15:00–16:00; net flow dominant one side 10m+.",
    trigger: "Break of 30m micro-range with accelerating prints.",
    invalidation: "Flow flip + VWAP cross against.",
    sessionWindow: { startEtHour: 15, startEtMin: 0, endEtHour: 15, endEtMin: 55 },
  },
];
